
TITLE = "Metadata extractor"
SAVE = "Save"
OPEN = "Open"
EXTRACT = "Extract"
DELETE = "Delete"

META_TITLE = "title"
META_NAMES = "names"
META_CONTENT = "content"
META_LOCATIONS = "locations"
META_KEYWORD = "keyword"
META_REF = "reference"

TYPE_TXT = "txt"
TYPE_ISO19115v2 = "iso19115v2"
TYPE_FGDC = "fgdc"

LABLE_NAME = "Name"
LABLE_ORGANISATION = "Organisation"
LABLE_PHONE = "Phone"
LABLE_FACS = "Facs"
LABLE_DELIVERY_POINT = "Delivery point"
LABLE_CITY = "City"
LABLE_AREA = "Area"
LABLE_POSTAL_CODE = "Postal code"
LABLE_COUNTRY = "Country"
LABLE_EMAIL = "Email"
LABLE_TYPE = "Type"

LABLE_WEST = "West"
LABLE_EAST = "East"
LABLE_NORTH = "North"
LABLE_SOUTH = "South"

LABLE_LINK = "Link"
LABLE_ORIGIN = "Origin"
LABLE_TITLE = "Title"
LABLE_DATE = "Date"

LABLE_DATE_BEGIN = "Date begin"
LABLE_DATE_END = "Date end"
LABLE_DESCRIPT_ABSTRACT = "Abstract"
LABLE_DESCRIPT_PURPOSE = "Purpose"
LABLE_DESCRIPT_SUPPLEMENTAL = "Supplemental"
LABLE_STATUS_PROGRESS = "Progress"
LABLE_POSTAL_STATUS_UPDATE = "Update"
LABLE_ACCESS = "Access"
LABLE_UUID = "UUID"
LABLE_CB_UUID = "Generate random UUID"
LABLE_LOCATION = "Locations"
LABLE_KEY_WORD = "Key words"

DIALOG_TITLE_ABOUT = "About"
DIALOG_TITLE_SETTINGS = "Settings"
DIALOG_BTN_OK = "OK"

LABLE_ABOUT_NAME = "Name"
LABLE_ABOUT_VERSION = "Version"
LABLE_ABOUT_AUTHOR = "Author"
LABLE_HOME_PAGE = "Home page"

TOOLTIP_DELETE_ELEMENT = "Delete element"
TOOLTIP_ADD_REFERENCE = "Add reference"
TOOLTIP_ADD_LOCATION = "Add location"
TOOLTIP_ADD_KEYWORD = "Add keyword"
TOOLTIP_ADD_PERSON = "Add person"
TOOLTIP_OPEN_PDF = "Open PDF"
TOOLTIP_SAVE_METADATA = "Save metadata"
TOOLTIP_EXTRACT_METADATA = "Extract metadata"


TAB_CONTROL = "Control"
TAB_INFO = "Info"
TAB_CONTACT = "Contact"
TAB_PERSON = "Person"
TAB_KEYWORD = "Keyword"
TAB_LOCATION = "Location"
TAB_REFERENCE = "Reference"

BTN_ADD = "Add"

MENU_ABOUT = "About"
MENU_EXIT = "Exit"
MENU_FILE = "&File"
MENU_QUESTION = "&?"
MENU_HELP = "Help"

MENU_LOAD = "Load"
MENU_FILE_LOAD = "Load file"
MENU_EXTRACT = "Extract"
MENU_SAVE = "Save"
MENU_OPEN = "Open"
MENU_SETTINGS = "Settings"

MENU_TOOLTIP_HELP = "Help"
MENU_TOOLTIP_ABOUT = "About"
MENU_TOOLTIP_OPEN_PDF = "Open pdf file"
MENU_TOOLTIP_LOAD_METADATA = "Load metadata"
MENU_TOOLTIP_LOAD_FILE_METADATA = "Load file metadata"
MENU_TOOLTIP_EXTRACT_METADATA = "Extract metadata"
MENU_TOOLTIP_SAVE_METADATA = "Save file with metadata"
MENU_TOOLTIP_EXIT = "Exit application"
MENU_TOOLTIP_SETTINGS = "Settings"

ICON_CLOSE = "data/icons/close.png"
ICON_OPEN = "data/icons/open.png"
ICON_SAVE = "data/icons/save.png"
ICON_PROCESS = "data/icons/process.png"
ICON_LOAD = "data/icons/load.png"
